version: '3.8'
services:
  build-frontend-dev:
    container_name: Frontend
    build:
      context: TemplateViteVue/
      dockerfile: Dockerfile
    ports:
      - 80:80
  build-backend-dev:
    container_name: Backend
    build:
      context: TemplateWebApi/
      dockerfile: TemplateWebApi/Dockerfile
    ports:
      - 92:8080
      - 93:8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
